menu:
- {name: 'papers', url: '/papers'}
- {name: 'vita', url: '/assets/CV_Ruolong Xiao.pdf'}
- {name: 'others', url: '/courses'}
# - {name: 'cv', url: '/cv'}

courses:
- {name: 'Price Theory', url: 'price-theory'}
- {name: 'Game Theory', url: 'game-theory'}
- {name: 'Political Economy', url: 'poli-econ'}

social:
- {icon: 'github', link: 'https://ruolongxiao.github.io'}
- {icon: 'twitter', link: 'https://twitter.com/xiaoruolong'}
- {icon: 'mail', link: 'ruolongxiao@gmail.com'}
- {icon: 'linkedin', link: 'https://linkedin.com/Ruolong Xiao'}

experiment_room:
- {name: Private notebook — draft results,
    url: /experiment-room/draft.html,
    description: Work-in-progress, not for sharing.}
- {name: Otree links,
    url: '/assets/user_links.md'}
    
#contacts:
#- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
